import type { WatchlistItem } from "./types";
import { toTopicSlug } from "./slug";

export const MOCK_WATCHLIST: WatchlistItem[] = [
  {
    id: "w-aapl",
    symbol: "AAPL",
    name: "Apple Inc.",
    type: "stock",
    topicSlug: toTopicSlug("AAPL"),
    addedAt: "2026-04-12T10:00:00Z",
    lastUpdated: "2026-06-03T14:30:00Z",
    latestSentiment: "positive",
    marketImpact: "medium",
    relatedStoriesCount: 3,
  },
  {
    id: "w-msft",
    symbol: "MSFT",
    name: "Microsoft Corporation",
    type: "stock",
    topicSlug: toTopicSlug("MSFT"),
    addedAt: "2026-04-15T10:00:00Z",
    lastUpdated: "2026-06-02T11:00:00Z",
    latestSentiment: "positive",
    marketImpact: "medium",
    relatedStoriesCount: 2,
  },
  {
    id: "w-nvda",
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    type: "stock",
    topicSlug: toTopicSlug("NVDA"),
    addedAt: "2026-04-18T10:00:00Z",
    lastUpdated: "2026-06-03T09:45:00Z",
    latestSentiment: "positive",
    marketImpact: "high",
    relatedStoriesCount: 4,
  },
  {
    id: "w-tsla",
    symbol: "TSLA",
    name: "Tesla, Inc.",
    type: "stock",
    topicSlug: toTopicSlug("TSLA"),
    addedAt: "2026-04-20T10:00:00Z",
    lastUpdated: "2026-06-02T09:15:00Z",
    latestSentiment: "negative",
    marketImpact: "high",
    relatedStoriesCount: 2,
  },
  {
    id: "w-spy",
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    type: "etf",
    topicSlug: toTopicSlug("SPY"),
    addedAt: "2026-04-22T10:00:00Z",
    lastUpdated: "2026-06-01T16:45:00Z",
    latestSentiment: "neutral",
    marketImpact: "high",
    relatedStoriesCount: 5,
  },
  {
    id: "w-qqq",
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    type: "etf",
    topicSlug: toTopicSlug("QQQ"),
    addedAt: "2026-04-25T10:00:00Z",
    lastUpdated: "2026-05-31T11:20:00Z",
    latestSentiment: "positive",
    marketImpact: "medium",
    relatedStoriesCount: 4,
  },
  {
    id: "w-vti",
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    type: "etf",
    topicSlug: toTopicSlug("VTI"),
    addedAt: "2026-05-01T10:00:00Z",
    lastUpdated: "2026-06-04T08:00:00Z",
    latestSentiment: "neutral",
    marketImpact: "medium",
    relatedStoriesCount: 3,
  },
  {
    id: "w-dia",
    symbol: "DIA",
    name: "SPDR Dow Jones Industrial Average ETF",
    type: "index",
    topicSlug: toTopicSlug("DIA"),
    addedAt: "2026-05-03T10:00:00Z",
    lastUpdated: "2026-06-04T08:00:00Z",
    latestSentiment: "neutral",
    marketImpact: "medium",
    relatedStoriesCount: 2,
  },
  {
    id: "w-ai",
    symbol: "AI Stocks",
    name: "Artificial intelligence equities",
    type: "sector",
    topicSlug: toTopicSlug("AI Stocks"),
    addedAt: "2026-05-08T10:00:00Z",
    lastUpdated: "2026-05-31T11:20:00Z",
    latestSentiment: "positive",
    marketImpact: "high",
    relatedStoriesCount: 5,
  },
  {
    id: "w-semi",
    symbol: "Semiconductors",
    name: "Semiconductor sector & chip supply chain",
    type: "sector",
    topicSlug: toTopicSlug("Semiconductors"),
    addedAt: "2026-05-10T10:00:00Z",
    lastUpdated: "2026-05-31T11:20:00Z",
    latestSentiment: "positive",
    marketImpact: "high",
    relatedStoriesCount: 4,
  },
  {
    id: "w-inflation",
    symbol: "Inflation",
    name: "Inflation, CPI & price trends",
    type: "topic",
    topicSlug: toTopicSlug("Inflation"),
    addedAt: "2026-05-12T10:00:00Z",
    lastUpdated: "2026-05-30T08:00:00Z",
    latestSentiment: "positive",
    marketImpact: "high",
    relatedStoriesCount: 3,
  },
  {
    id: "w-rates",
    symbol: "Interest Rates",
    name: "Fed policy, yields & rate expectations",
    type: "topic",
    topicSlug: toTopicSlug("Interest Rates"),
    addedAt: "2026-05-14T10:00:00Z",
    lastUpdated: "2026-06-01T16:45:00Z",
    latestSentiment: "neutral",
    marketImpact: "high",
    relatedStoriesCount: 4,
  },
  {
    id: "w-xlk",
    symbol: "XLK",
    name: "Technology Select Sector SPDR Fund",
    type: "sector",
    topicSlug: toTopicSlug("XLK"),
    addedAt: "2026-05-18T10:00:00Z",
    lastUpdated: "2026-05-29T13:00:00Z",
    latestSentiment: "neutral",
    marketImpact: "medium",
    relatedStoriesCount: 2,
  },
  {
    id: "w-smh",
    symbol: "SMH",
    name: "VanEck Semiconductor ETF",
    type: "etf",
    topicSlug: toTopicSlug("SMH"),
    addedAt: "2026-05-22T10:00:00Z",
    lastUpdated: "2026-05-31T11:20:00Z",
    latestSentiment: "positive",
    marketImpact: "medium",
    relatedStoriesCount: 3,
  },
];

/** Suggestions shown in the mock add-to-watchlist UI */
export const WATCHLIST_SUGGESTIONS = [
  { symbol: "GOOGL", name: "Alphabet Inc.", type: "stock" as const },
  { symbol: "AMZN", name: "Amazon.com, Inc.", type: "stock" as const },
  { symbol: "META", name: "Meta Platforms, Inc.", type: "stock" as const },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", type: "etf" as const },
  { symbol: "Energy", name: "Energy sector & oil markets", type: "sector" as const },
  { symbol: "Fed Policy", name: "Federal Reserve & FOMC", type: "topic" as const },
];
